### ISSUE TITLE
Where does development happen?

### ISSUE THREAD

**Issue by matthijskooijman** [OpenTTD/grfcodec#3]
https://dev.openttdcoop.org/projects/grfcodec points to github, but the README here points back to ottdc. Should the README be updated?

Also, what is the official download location? There is a list of tags with source tarballs here (which are just git snapshots), but there is also https://www.openttd.org/downloads/grfcodec-releases/latest.html that has binaries (and possibly post-processed) source tarballs?

**Comment by glx22** [comment]
I think the readme needs to be updated. Code also miss support for the recent additions in newgrf specs.

**Comment by serprinss** [comment]
looks like development happens here since #1 appears to be merged here
